import PDFDocument from "pdfkit";
import { AppliedTaxSnapshot } from "../../shared/utils/taxCalculator";
import { settingsService } from "../settings/settings.service";

export interface InvoicePdfData {
  number: string;
  issueDate: Date | string;
  dueDate: Date | string;
  status: string;
  currency: string;
  subtotal: number;
  totalAdditiveTax: number;
  totalDeductionTax: number;
  grandTotal: number;
  netPayable: number;
  total: number;
  amountPaid: number;
  balanceDue: number;
  notes?: string | null;
  terms?: string | null;
  client: {
    companyName: string;
    contactPerson: string;
    email: string;
    phone: string;
    gstNumber?: string | null;
    billingAddress?: string | null;
    state?: string | null;
  };
  items: Array<{
    description: string;
    quantity: number;
    unitPrice: number;
    lineAmount: number;
    appliedTaxes: AppliedTaxSnapshot[];
    total: number;
  }>;
}

export const generateInvoicePdfBuffer = async (data: InvoicePdfData): Promise<Buffer> => {
  const settings = await settingsService.getSettings();
  const companyTitle = settings.companyName || "LEDGERLY";
  const footerText = settings.defaultEmailFooter || "Thank you for your business! Generated by Ledgerly Invoicing System.";

  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 40, size: "A4" });
      const buffers: Buffer[] = [];

      doc.on("data", (chunk) => buffers.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(buffers)));
      doc.on("error", (err) => reject(err));

      const currencySymbol = data.currency === "INR" ? "INR " : `${data.currency} `;

      // Header Brand Accent
      doc.rect(0, 0, 600, 12).fill("#F97316");

      // Company Title & Header
      doc.fillColor("#0F172A").fontSize(18).font("Helvetica-Bold").text(companyTitle, 40, 30);
      doc.fillColor("#64748B").fontSize(8).font("Helvetica").text(`${settings.businessEmail} | ${settings.phone}`, 40, 52);

      // Invoice Number & Status Box
      doc.fillColor("#0F172A").fontSize(18).font("Helvetica-Bold").text(data.number, 400, 30, { align: "right" });
      doc.fillColor("#F97316").fontSize(10).font("Helvetica-Bold").text(`STATUS: ${data.status}`, 400, 52, { align: "right" });

      doc.moveTo(40, 75).lineTo(555, 75).strokeColor("#E2E8F0").lineWidth(1).stroke();

      // Bill To & Invoice Info Columns
      const yInfo = 90;
      doc.fillColor("#64748B").fontSize(9).font("Helvetica-Bold").text("BILLED TO:", 40, yInfo);
      doc.fillColor("#0F172A").fontSize(11).font("Helvetica-Bold").text(data.client.companyName, 40, yInfo + 14);
      doc.fillColor("#334155").fontSize(9).font("Helvetica").text(`Attn: ${data.client.contactPerson}`, 40, yInfo + 28);
      doc.text(`Email: ${data.client.email}`, 40, yInfo + 40);
      doc.text(`Phone: ${data.client.phone}`, 40, yInfo + 52);
      if (data.client.gstNumber) {
        doc.text(`GSTIN: ${data.client.gstNumber}`, 40, yInfo + 64);
      }
      if (data.client.billingAddress) {
        doc.text(`Address: ${data.client.billingAddress}`, 40, yInfo + (data.client.gstNumber ? 76 : 64));
      }

      // Dates Column
      const issueDateStr = new Date(data.issueDate).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" });
      const dueDateStr = new Date(data.dueDate).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" });

      doc.fillColor("#64748B").fontSize(9).font("Helvetica-Bold").text("INVOICE DETAILS:", 360, yInfo);
      doc.fillColor("#334155").fontSize(9).font("Helvetica").text("Issue Date:", 360, yInfo + 14);
      doc.fillColor("#0F172A").font("Helvetica-Bold").text(issueDateStr, 440, yInfo + 14);
      doc.fillColor("#334155").font("Helvetica").text("Due Date:", 360, yInfo + 28);
      doc.fillColor("#0F172A").font("Helvetica-Bold").text(dueDateStr, 440, yInfo + 28);
      doc.fillColor("#334155").font("Helvetica").text("Currency:", 360, yInfo + 42);
      doc.fillColor("#0F172A").font("Helvetica-Bold").text(data.currency, 440, yInfo + 42);

      // Items Table Header
      let yTable = yInfo + 110;
      doc.rect(40, yTable, 515, 22).fill("#F8FAFC");
      doc.fillColor("#475569").fontSize(9).font("Helvetica-Bold");
      doc.text("ITEM DESCRIPTION", 48, yTable + 6);
      doc.text("QTY", 270, yTable + 6, { width: 40, align: "right" });
      doc.text("PRICE", 320, yTable + 6, { width: 55, align: "right" });
      doc.text("TAXES", 380, yTable + 6, { width: 95, align: "left" });
      doc.text("AMOUNT", 480, yTable + 6, { width: 65, align: "right" });

      yTable += 28;

      // Table Rows
      doc.font("Helvetica").fontSize(9).fillColor("#1E293B");
      data.items.forEach((item) => {
        if (yTable > 700) {
          doc.addPage();
          yTable = 40;
        }

        const taxesStr = item.appliedTaxes && item.appliedTaxes.length > 0
          ? item.appliedTaxes.map((t) => `${t.taxCode} (${t.taxRate}${t.type === "PERCENTAGE" ? "%" : ""})`).join(", ")
          : "No Tax";

        const lineAmt = item.lineAmount || item.quantity * item.unitPrice;

        doc.text(item.description, 48, yTable, { width: 215 });
        doc.text(item.quantity.toString(), 270, yTable, { width: 40, align: "right" });
        doc.text(`${item.unitPrice.toFixed(2)}`, 320, yTable, { width: 55, align: "right" });
        doc.text(taxesStr, 380, yTable, { width: 95, align: "left" });
        doc.text(`${lineAmt.toFixed(2)}`, 480, yTable, { width: 65, align: "right" });

        yTable += 22;
        doc.moveTo(40, yTable - 4).lineTo(555, yTable - 4).strokeColor("#F1F5F9").lineWidth(0.5).stroke();
      });

      yTable += 10;

      // Totals Box
      if (yTable > 660) {
        doc.addPage();
        yTable = 40;
      }

      doc.rect(330, yTable, 225, 130).fill("#F8FAFC").strokeColor("#E2E8F0").lineWidth(1).stroke();

      let ySummary = yTable + 10;
      const drawSummaryRow = (label: string, value: string, isBold: boolean = false, color: string = "#0F172A") => {
        doc.font(isBold ? "Helvetica-Bold" : "Helvetica")
           .fillColor(color)
           .fontSize(9)
           .text(label, 340, ySummary);
        doc.text(value, 450, ySummary, { width: 95, align: "right" });
        ySummary += 18;
      };

      drawSummaryRow("Subtotal:", `${currencySymbol}${data.subtotal.toFixed(2)}`);
      if (data.totalAdditiveTax > 0) {
        drawSummaryRow("Total Additive Tax:", `+${currencySymbol}${data.totalAdditiveTax.toFixed(2)}`, false, "#16A34A");
      }
      drawSummaryRow("Grand Total:", `${currencySymbol}${data.grandTotal.toFixed(2)}`, true);
      if (data.totalDeductionTax > 0) {
        drawSummaryRow("TDS / Deduction Tax:", `-${currencySymbol}${data.totalDeductionTax.toFixed(2)}`, false, "#DC2626");
      }
      drawSummaryRow("Net Payable:", `${currencySymbol}${data.netPayable.toFixed(2)}`, true, "#2563EB");
      drawSummaryRow("Balance Due:", `${currencySymbol}${data.balanceDue.toFixed(2)}`, true);

      // Notes & Terms
      if (data.notes || data.terms) {
        let yNotes = yTable + 10;
        if (data.notes) {
          doc.fillColor("#64748B").fontSize(9).font("Helvetica-Bold").text("NOTES / REMARKS:", 40, yNotes);
          doc.fillColor("#334155").font("Helvetica").fontSize(8).text(data.notes, 40, yNotes + 12, { width: 270 });
          yNotes += 40;
        }
        if (data.terms) {
          doc.fillColor("#64748B").fontSize(9).font("Helvetica-Bold").text("TERMS & CONDITIONS:", 40, yNotes);
          doc.fillColor("#334155").font("Helvetica").fontSize(8).text(data.terms, 40, yNotes + 12, { width: 270 });
        }
      }

      // Footer
      doc.fillColor("#94A3B8").fontSize(8).font("Helvetica").text(footerText, 40, 780, { align: "center" });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
};
